### ISSUE TITLE
Meta Report Issue

### ISSUE THREAD

**Issue by matiasbavera** [open-rmf/rmf-web#255]
It would be nice to have these static structure reports:

- [ ] charger states. 
- [x] door states. Related issue #254  
- [ ] error / warning messages
- [x] lift states. Related issue #260 
- [ ] negotiations succeed/failed
- [x] robot states. Related issue #253 
- [ ] robot motion plans (great schedule dumps)
- [ ] robot actions (sounds, bays open/close, …). Related issue #257 
- [ ] user actions. Related issue #258 
- [x] tasks issued/completed/failed. Related issue #259 
- [ ] workcell states. Relared issue #256
- [x] user Authentication (logins / logouts / login-failures) #261 

This is not a closed list, more reports can be added.

**Comment by aaronchongth** [comment]
Reporting removed via https://github.com/open-rmf/rmf-web/pull/628
