### ISSUE TITLE
Spring Cleaning (meta issue)

### ISSUE THREAD

**Issue by koonpeng** [open-rmf/rmf-web#308]
### Deprecated and unused packages
react-components:
- [x] moment, deprecated
- [x] awesome-typescript-loader, outdated typescript peer dep, archived repo
- [x] istanbul-instrumenter-loader, outdated webpack peer dep, archived repo, also shouldn't this be in devdeps?

dashboard:
- [x] styled-components, do we really need this since we are mostly using @material-ui/styles?
- [x] gh-pages, publishing to gh pages is no longer feasible as this has become a full stack app
- [x] react-test-renderer, do we need this since we are using @testing-library/react?
- [x] @msgpack/msgpack, don't need this anymore as we are no longer using ros2-bridge
- [x] typeface-roboto, deprecated, use @fontsource/roboto instead

ros2-bridge:
- [x] move this to its own repo because we are no longer using ros2-bridge in any of the packages

rmf-auth:
- [x] gh-pages, don't think this is used
- [x] react-test-renderer, do we need this since we are using @testing-library/react?
- [x] styled-components, do we really need this since we are mostly using @material-ui/styles?
- [x] typeface-roboto, deprecated, use @fontsource/roboto instead

### Re-organizing
- [x] move e2e to it's own package outside dashboard

### Others
- [x] migrate to ~yarn~ lerna, removing the existing bootstrap scripts
- [x] generate pylintrc files, pylint doesn't support inheriting configs like eslint, but it does support generating a config file based on another.
- [x] look at improving the e2e test flow, remove authentication for most tests, run authentication tests separately. Combine multiple test suites to avoid restarting the browser/session unnecessarily.
- [ ] rename packages, currently blocked. Need to know which registry we are publishing to and the organization name, if any.
- [ ] rename `api-server` to `rmf-server`, also see above on org name
- [ ] rename `api-client` to `rmf-client`, also see above on org name

**Comment by koonpeng** [comment]
closing this as most of the issues have been resolved, the remaining ones require knowledge about the release process, which shall be determined when the time comes.
