### ISSUE TITLE
perennial list: prototyping tasks

### ISSUE THREAD

**Issue by vallq** [open-rmf/rmf-web#522]
**theme**
- [x] standardise the theme colors (#520)

**dashboard**
- all relevant tabs
- [x] on-screen alert notification (#517) 
- [x] clicking of icon centers the map (#503)
- [ ] different traj colors for diff robot modes (#501)
- [x] updating the links between the light and dark mode toggles

- task tab
- [x] filtering functions for task tab (#506)

- infrastructure tab (#505)
- [x] handling layout when there are more components (doors, workcells) than the display can show

- overview tab (#502)
- [x] task panel to have 3 columns `In Progress`, `Queued`, `Completed`
- [x] horizontal scrolling for information summary panel (edit: made this 3 columns with vertical scrolling)
- [x] data visualisation to cover `breakdown of job types`, `avg time spent at charging docks`, `time spent on tasks`
- [ ] configurable panels? //mosaic lib not compatible with mui themes

- robot tab
- [x] interactive map to fill the height of the app
- [x] swap positions of `Battery` and `Task Progress`, alongside visual representation

**Comment by aaronchongth** [comment]
Closing since we have individual tickets for the remaining tasks,
#501 and https://github.com/open-rmf/rmf-web/pull/526
