### ISSUE TITLE
Task Redesign

### ISSUE THREAD

**Issue by aaronchongth** [open-rmf/rmf-web#567]
### Description

This directly related to the efforts in https://github.com/open-rmf/rmf_ros2/issues/107.

- [x] https://github.com/open-rmf/rmf-web/issues/556
- [x] https://github.com/open-rmf/rmf-web/issues/555
- [x] https://github.com/open-rmf/rmf-web/issues/557
- [x] Changes in `api-server` to support requests, cancellation and other task related calls.
- [x] Migrate `dashboard` main task request forms to use the new data models.
- [ ] Changes to `dashboard` to allow users to compose flexible tasks and send requests.
- [x] Changes to `dashboard` to allow users to cancel or perform any other new task related calls.

### Implementation considerations

* Any development and testing should be targeted at `prototype/task_v2-2`

### Additional information

* Architectural changes were needed, and has since been backported into `main`, https://github.com/open-rmf/rmf-web/pull/565
* Branch `prototype/task_v2-2` targets `main` after the backport.

**Comment by aaronchongth** [comment]
Per VC,
* Task logs and phase logs are not displayed in the prototype, this should be decided and put into the prototype if needed.
* Other fields in the prototype, `start_waypoint` and `finish_waypoint`, etc, are not readily available in the Task state or logs, should this be parsed from the event logs, or be placed into the schema?

**Comment by mayman99** [comment]
> Other fields in the prototype, start_waypoint and finish_waypoint, etc, are not readily available in the Task state or logs, should this be parsed from the event logs, or be placed into the schema?

@mxgrey is there currently a plan to add them to the schema or do we try to infer them on the frontend/api server side?

**Comment by mxgrey** [comment]
My most recent stance on this is to not include this information on the dashboard until there's a concrete request/requirement for it related to a project or deployment.

To me personally, it's not obvious that knowing where the robot was at the start of a task or will be at the end of a task is important enough information to include in the high level overview. Especially because I can imagine that some tasks won't have a definite endpoint, for example an infinite patrolling task.

If anyone feels differently and believes we ought to include that information I'm genuinely open to hearing that opinion and figuring out the "right" way to provide that information. Maybe it can be an optional field which we display if the information is available, but leave blank (or say `unknown`) when the information is not available. And maybe we should provide that information per phase instead of per task.

**Comment by aaronchongth** [comment]
Closing this as the remaining feature of composing and dispatching flexible tasks can be tracked separately, https://github.com/open-rmf/rmf-web/issues/554
